
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int i_return = 9;
  public static final int cadena = 21;
  public static final int coma = 17;
  public static final int i_else = 6;
  public static final int i_stdin = 10;
  public static final int constante = 2;
  public static final int llave_izq = 14;
  public static final int booleano = 19;
  public static final int llave_der = 15;
  public static final int i_elseif = 5;
  public static final int operador_aritmetico = 22;
  public static final int asignacion = 3;
  public static final int operador_relacional = 23;
  public static final int EOF = 0;
  public static final int i_stdout = 11;
  public static final int error = 1;
  public static final int i_func = 8;
  public static final int i_if = 4;
  public static final int entero = 20;
  public static final int fin_instruccion = 16;
  public static final int parentesis_izq = 12;
  public static final int i_while = 7;
  public static final int operador_logico = 24;
  public static final int identificador = 18;
  public static final int parentesis_der = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "constante",
  "asignacion",
  "i_if",
  "i_elseif",
  "i_else",
  "i_while",
  "i_func",
  "i_return",
  "i_stdin",
  "i_stdout",
  "parentesis_izq",
  "parentesis_der",
  "llave_izq",
  "llave_der",
  "fin_instruccion",
  "coma",
  "identificador",
  "booleano",
  "entero",
  "cadena",
  "operador_aritmetico",
  "operador_relacional",
  "operador_logico"
  };
}

